name: mess
description: Messaging as simple as it can be
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  adaptive_breakpoints: ^0.1.7
  awesome_bottom_bar: ^1.2.4
  collection: ^1.18.0
  crypto: ^3.0.3
  drift: ^2.18.0
  envied: ^0.5.4+1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_hooks: ^0.20.5
  form_builder_image_picker: ^4.0.0
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.1.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  hooks_riverpod: ^2.5.1
  icloud_storage: ^2.2.0
  icons_plus: ^5.0.0
  json_annotation: ^4.9.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^6.1.0
  sliver_tools: ^0.2.12
  sqlite3_flutter_libs: ^0.5.21
  supabase_flutter: ^2.5.2
  web_socket_channel: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  drift_dev: ^2.18.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
